name: CI FastAPI Backend

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to check out your repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify your Python version (e.g., '3.9', '3.10', '3.11')
          cache: 'pip' # Caches pip dependencies for faster builds
          cache-dependency-path: 'requirements.txt' # Path to your requirements file

      - name: Install dependencies
        run: pip install -r requirements.txt # Install packages from requirements.txt

      # This step uses the secret created in GitHub repo settings
      - name: Set GOOGLE_API_KEY environment variable
        run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV
        # Why $GITHUB_ENV? This makes the variable available for subsequent steps in the same job.
        # It's important for tools that might need the key for validation/tests.

      # - name: Run tests (optional)
      #   run: pytest # Uncomment if you have tests and pytest installed

      # - name: Run linting (optional)
      #   run: flake8 . # Uncomment if you use a linter like flake8